export const COUNTRIES = [
  'Armenia',
  'Belarus',
  'Bulgaria',
  'Canada',
  'Cyprus',
  'Denmark',
  'England',
  'France',
  'Georgia',
  'Germany',
  'Hungary',
  'Israel',
  'Italy',
  'Kazakhstan',
  'Kyrgyzstan',
  'Lithuania',
  'Moldova',
  'Montenegro',
  'Poland',
  'Russia',
  'Serbia',
  'South Korea',
  'Spain',
  'Sweden',
  'Switzerland',
  'Thailand',
  'Turkey',
  'Ukraine',
  'United States',
  'Uzbekistan',
] as const;

export type Country = (typeof COUNTRIES)[number];
