export const FORM = {
  FIELDS: {
    NAME: 'name',
    AGE: 'age',
    EMAIL: 'email',
    GENDER: 'gender',
    TERMS: 'terms',
    GENDER_VALUES: {
      MALE: 'male',
      FEMALE: 'female',
    },
    PASSWORD: 'password',
    CONFIRM_PASSWORD: 'confirmPassword',
    AVATAR: 'avatar',
    COUNTRY: 'country',
  },
  LABELS: {
    NAME: 'Name',
    AGE: 'Age',
    EMAIL: 'Email',
    GENDER: 'Gender',
    MALE: 'Male',
    FEMALE: 'Female',
    TERMS: 'Accept Terms & Conditions',
    SUBMIT: 'Submit',
    PASSWORD: 'Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    AVATAR: 'Avatar',
    COUNTRY: 'Country',
  },
} as const;
